version: '3'

services:
  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: docs_db
    ports:
      - 5433:5432
    volumes:
      - ./temp/dev/db-data:/var/lib/postgresql/data
  
  redis:
    image: redis:5-alpine
    volumes:
      - ./temp/dev/redis:/data

  app:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - ./docker/dev/env/.env
    ports:
      - "3080:3080"
    volumes:
      - ./src:/src
    depends_on:
      - db
      - redis


